### ISSUE TITLE
How to add support for iOS 13 (< 13.4)

### ISSUE THREAD

**Issue by zx500xl** [NyaMisty/fouldecrypt#5]
Hey! You did an amazing job! Thank you so much! 
Could you help me add support for iOS 13? How exactly do I get the correct offsets for structures in kernstructs.hpp?

**Comment by NyaMisty** [comment]
I've noted how to find those offset in the comment.
Combining with XNU's source code ([darwin/xnu](https://github.com/apple/darwin-xnu)), you can find them ;)

**Comment by zx500xl** [comment]
Yeah, I’ve seen them ;) where did you find kernel source code? I mean for particular iOS version?

**Comment by NyaMisty** [comment]
There aren't iOS kernel source code. Usually iOS's function are the same as MacOS one.
Functions' funcnality doesn't change very much

**Comment by zx500xl** [comment]
Anyway, could you help me with it? I'm not asking to do this for me, I'm just asking for more detailed instructions. I can test various devices with iOS 13
